= Tc2026.1 Desarrollo de aplicaciones web

_Tecnológico de Monterrey, Estado de México._

Este proyecto contiene todos los archivos fuente que el profesor irá generando en clase durante el semestre agosto-diciembre del 2016.

Los archivos se pueden consultar directamente en este mismo sitio, o se puede usar `git` para obtener una copia local de éstos. En este último caso se deben seguir los siguiente pasos:

1. Si es necesario, http://git-scm.com/downloads[instalar un cliente git] en tu computadora. La plataforma http://c9.io/[Cloud 9] ya cuenta con `git` instalado.

2. Clonar este repositorio. Desde la terminal teclear:
    
    git clone https://github.com/ariel-ortiz/201713-tc2026.3.git tc2026
    
3. Cambiarse al directorio `tc2026`:
    
    cd tc2026
+    
En dicho directorio encontrás todos los archivos fuente del proyecto.
    
4. Cada vez que el profesor realice modificaciones a archivos existentes o agregue archivos nuevos, será necesario hacer un *pull* al repositorio. En la terminal y desde el directorio `tc2026` teclear: 
    
    git pull